<template>
  <ListingHeaderTemplate>
    <div class="sorting flex3">
      <label v-if="selectionEnabled" class="check-label">
        <input
          type="checkbox"
          :checked="selected"
          @click="$emit('selection-change', $event.target.checked)"
        />
        <span class="check-span"></span>
      </label>
    </div>
    <div class="share-url sorting no-pointer flex30">
      <span>Shared URLs</span>
    </div>
    <div class="share-title sorting flex11">
      <span>Title</span>
    </div>
    <div class="share-desc sorting flex20">
      <span>Description</span>
    </div>
    <div
      class="generated-date sorting flex10"
      :class="sortingClass('updated_at')"
    >
      <span @click="$emit('sort', 'updated_at')">Generated Date</span>
    </div>
    <div class="generated-by sorting flex10" :class="sortingClass('userName')">
      <span @click="$emit('sort', 'userName')">Generated By </span>
    </div>
    <div
      class="generated-source sorting flex10"
      :class="sortingClass('generated_source')"
    >
      <span @click="$emit('sort', 'generated_source')">Generated Source</span>
    </div>
    <div class="categary-action text-right sorting no-pointer flex6">
      <span>Action</span>
    </div>
  </ListingHeaderTemplate>
</template>

<script>
import ListingHeaderTemplate from '../ListingHeaderTemplate'

export default {
  components: { ListingHeaderTemplate },
  extends: ListingHeaderTemplate,
  props: {
    selected: { type: Boolean, default: false },
    selectionEnabled: { type: Boolean, default: true },
  },
}
</script>
