<template>
  <ListingHeaderTemplate>
    <div class="sorting flex3">
      <label class="check-label">
        <input
          type="checkbox"
          :checked="selected"
          @click="$emit('selection-change', $event.target.checked)"
        />
        <span class="check-span"></span>
      </label>
    </div>
    <div class="share-url sorting no-pointer flex71">
      <span>Embedded URL </span>
    </div>
    <div
      class="generated-date sorting flex10"
      :class="sortingClass('embed_code_date')"
    >
      <span @click="$emit('sort', 'embed_code_date')">Generated Date</span>
    </div>
    <div class="generated-by sorting flex10" :class="sortingClass('userName')">
      <span @click="$emit('sort', 'userName')">Generated By </span>
    </div>
    <div class="share-actions sorting no-pointer flex6">
      <span>Action</span>
    </div>
  </ListingHeaderTemplate>
</template>

<script>
import ListingHeaderTemplate from '../ListingHeaderTemplate'

export default {
  components: { ListingHeaderTemplate },
  extends: ListingHeaderTemplate,
  props: {
    selected: { type: Boolean, default: false },
  },
}
</script>
