<template>
  <div class="general-settings-right h-100">
    <div class="newAnalytics tableDetail customscrollbar">
      <div class="breadcrumb-links">
        <ul>
          <li>
            <a @click="$emit('backToGraph')">
              <svg
                id="Layer_1"
                class="back-icon blue mr-1"
                version="1.1"
                xmlns="http://www.w3.org/2000/svg"
                xmlns:xlink="http://www.w3.org/1999/xlink"
                x="0px"
                y="0px"
                viewBox="0 0 18 18"
                xml:space="preserve"
              >
                <g id="Group_4468" transform="translate(-577 -181)">
                  <rect
                    id="Rectangle_3007"
                    x="577"
                    y="181"
                    class="fill-hide"
                    width="18"
                    height="18"
                  ></rect>
                  <g id="Group_4425" transform="translate(-514.168 -476.583)">
                    <path
                      id="Icon_material-backspace"
                      class="fill-color"
                      d="M1107.7,659.8h-11.3c-0.5,0-0.9,0.3-1.2,0.7l-4.1,6.1l4.1,6.1c0.3,0.4,0.7,0.7,1.2,0.7h11.3c0.8,0,1.5-0.7,1.5-1.5v-10.5C1109.2,660.5,1108.5,659.8,1107.7,659.8z"
                    ></path>
                    <g id="Group_4424">
                      <g id="Group_4422">
                        <path
                          id="Path_3527"
                          class="fill-white"
                          d="M1099.7,669.8c-0.4,0-0.7-0.3-0.7-0.8c0-0.2,0.1-0.4,0.2-0.5l5-5c0.3-0.3,0.8-0.3,1.1,0c0.3,0.3,0.3,0.7,0,1l-5,5C1100.1,669.8,1099.9,669.8,1099.7,669.8z"
                        ></path>
                      </g>
                      <g id="Group_4423">
                        <path
                          id="Path_3528"
                          class="fill-white"
                          d="M1104.7,669.8c-0.2,0-0.4-0.1-0.5-0.2l-5-5c-0.3-0.3-0.3-0.8,0-1.1c0.3-0.3,0.8-0.3,1.1,0c0,0,0,0,0,0l5,5c0.3,0.3,0.3,0.8,0,1.1C1105.1,669.8,1104.9,669.8,1104.7,669.8L1104.7,669.8z"
                        ></path>
                      </g>
                    </g>
                  </g>
                </g>
              </svg>
              Shared Asset Analytics
            </a>
          </li>
          <li>
            <span>{{ collectionBreadcrumbsHeader }}</span>
          </li>
        </ul>
      </div>
      <div class="d-flex align-items-end justify-content-between mb2">
        <ul class="assetsType">
          <li>
            <span>Filter By : </span>
            <div class="search-by">
              <Select2
                class="select2-hidden-accessible"
                :value="categoryBy"
                :options="categoryList"
                :attrs="{ minimumResultsForSearch: -1 }"
                @input="changeCategory"
              />
            </div>
          </li>
          <li>
            <span>Type : </span>
            <div class="search-by">
              <Select2
                class="select2-hidden-accessible"
                :value="collectionsType"
                :options="collectionTypeList"
                :attrs="{ minimumResultsForSearch: -1 }"
                @input="changeCategoryByCollection"
              />
            </div>
          </li>
          <li>
            <span>View By : </span>
            <div class="search-by">
              <Select2
                class="select2-hidden-accessible"
                :value="categoryByShared"
                :options="sharedTypeList"
                :attrs="{ minimumResultsForSearch: -1 }"
                @input="changeCategoryByShared"
              />
            </div>
          </li>
        </ul>
      </div>
      <!--  View By - Shared URL  -->
      <div v-if="viewedBy == 'shared url'" class="common-box bg-gray">
        <div class="table-list-view small-height table-list-scrolling">
          <ul v-if="sharedUrlList.length" class="thead">
            <li>
              <div class="categary-name sorting flex40">
                <span>Shared URL</span>
              </div>
              <div class="user-type sorting flex10">
                <span>Generated By</span>
              </div>
              <div class="generated-date sorting flex10">
                <span>Generated Date</span>
              </div>
              <div class="generated-source sorting flex10">
                <span>Generated Source</span>
              </div>
              <div class="no-asset sorting flex10 text-center">
                <span>Number of Asset</span>
              </div>
              <div class="url-count sorting flex10 text-center">
                <span>Total Impressions</span>
              </div>
              <div class="total-download sorting flex10 text-center">
                <span>Total Download</span>
              </div>
            </li>
          </ul>
          <div class="customscrollbar no_footer">
            <ul class="tbody">
              <li
                v-for="(url, index) in sharedUrlList"
                :key="url.id"
                class="collectionURL h-auto open"
              >
                <div class="w-100 d-flex align-items-center">
                  <a
                    :href="`#url${index}${url.id}`"
                    aria-expanded="false"
                    data-toggle="collapse"
                    @click.prevent="getSharedUrlAssetsDetails(index, url)"
                  >
                    <svg
                      id="Layer_1"
                      class="toggle-icon"
                      version="1.1"
                      xmlns="http://www.w3.org/2000/svg"
                      xmlns:xlink="http://www.w3.org/1999/xlink"
                      x="0px"
                      y="0px"
                      viewBox="0 0 18 18"
                      xml:space="preserve"
                    >
                      <g id="Group_4481" transform="translate(-871 -754)">
                        <rect
                          id="Rectangle_3019"
                          x="871"
                          y="754"
                          class="fill-hide"
                          width="18"
                          height="18"
                        />
                        <path
                          id="Path_3404"
                          class="fill-color"
                          d="M880,768.6c-0.5,0-1-0.2-1.3-0.6l-7.1-7.1c-0.7-0.7-0.7-1.9,0-2.7c0.4-0.3,0.8-0.5,1.3-0.5h14.2c1,0,1.9,0.9,1.9,1.9c0,0.5-0.2,1-0.6,1.3l-7.1,7.1C881,768.4,880.5,768.6,880,768.6L880,768.6z M872.9,759.3c-0.2,0-0.3,0.1-0.3,0.3c0,0.1,0,0.2,0.1,0.2l7.1,7.1c0.1,0.1,0.1,0.1,0.2,0.1c0.1,0,0.2,0,0.2-0.1l7.1-7.1c0.1-0.1,0.1-0.3,0-0.4c0,0,0,0,0,0c0-0.1-0.1-0.1-0.2-0.1L872.9,759.3z"
                        />
                      </g>
                    </svg>
                  </a>
                  <div class="categary-name tb-column flex40">
                    <div class="top-column">
                      <span>{{
                        url.share_url | normalizedUrl(url.generated_source)
                      }}</span>
                    </div>
                  </div>

                  <!--                  <div class="collection tb-column flex10">
                    <div class="top-column">
                      <label>{{
                        collectionsType == 'collection'
                          ? 'Collection'
                          : 'Non Collection'
                      }}</label>
                    </div>
                  </div>-->
                  <div class="user-type tb-column flex10">
                    <div class="top-column">
                      <label>{{ url.user ? url.user.name : '-' }}</label>
                    </div>
                  </div>
                  <div class="generated-date tb-column flex10">
                    <div class="top-column">
                      <label>{{
                        $moment(url.created_at).format('Do, MMM YYYY')
                      }}</label>
                    </div>
                  </div>
                  <div class="generated-source tb-column flex10">
                    <div class="top-column">
                      <label>{{
                        url.generated_source | normalizedSource
                      }}</label>
                    </div>
                  </div>

                  <div class="no-asset tb-column flex10 text-center">
                    <div class="top-column">
                      <label>{{
                        url.total_assets ? url.total_assets : 0
                      }}</label>
                    </div>
                  </div>
                  <div class="url-count tb-column flex10 text-center">
                    <div class="top-column">
                      <label>{{ url.total_visited }}</label>
                    </div>
                  </div>
                  <div class="total-download tb-column flex10 text-center">
                    <div class="top-column">
                      <label>{{ url.total_download }}</label>
                    </div>
                  </div>
                </div>
                <div class="h-auto w-100 mt0">
                  <div :id="`url${index}${url.id}`" class="collapse w-100">
                    <div v-if="assetsDynamicIndex == index" class="dataLoader">
                      <svg
                        id="Layer_1"
                        class="refresh-icon fa-spin"
                        version="1.1"
                        xmlns="http://www.w3.org/2000/svg"
                        xmlns:xlink="http://www.w3.org/1999/xlink"
                        x="0px"
                        y="0px"
                        viewBox="0 0 18 18"
                        xml:space="preserve"
                      >
                        <g id="Group_4491" transform="translate(-1206 -466)">
                          <rect
                            id="Rectangle_3030"
                            x="1206"
                            y="466"
                            class="fill-white"
                            width="18"
                            height="18"
                          ></rect>
                          <g
                            id="Icon_feather-refresh-cw"
                            transform="translate(-369.921 -994.994)"
                          >
                            <g id="Path_3566">
                              <path
                                id="Path_3569"
                                class="fill-color"
                                d="M1593.2,1469.2h-4.5c-0.4,0-0.7-0.3-0.7-0.7c0-0.4,0.3-0.7,0.7-0.7h3.8v-3.8c0-0.4,0.3-0.7,0.7-0.7s0.7,0.3,0.7,0.7v4.5C1593.9,1468.9,1593.6,1469.2,1593.2,1469.2z"
                              ></path>
                            </g>
                            <g id="Path_3567">
                              <path
                                id="Path_3570"
                                class="fill-color"
                                d="M1576.7,1476.7c-0.4,0-0.7-0.3-0.7-0.7v-4.5c0-0.4,0.3-0.7,0.7-0.7h4.5c0.4,0,0.7,0.3,0.7,0.7s-0.3,0.7-0.7,0.7h-3.8v3.8C1577.4,1476.4,1577.1,1476.7,1576.7,1476.7z"
                              ></path>
                            </g>
                            <g id="Path_3568">
                              <path
                                id="Path_3571"
                                class="fill-color"
                                d="M1584.9,1477.5c-2,0-3.9-0.8-5.3-2.2l-3.5-3.3c-0.3-0.3-0.3-0.7,0-1c0.3-0.3,0.7-0.3,1,0l3.5,3.3c2.3,2.4,6.2,2.4,8.5,0c0.6-0.6,1.1-1.4,1.4-2.3c0.1-0.4,0.5-0.6,0.9-0.5c0.4,0.1,0.6,0.5,0.5,0.9c0,0,0,0,0,0C1590.9,1475.5,1588.1,1477.5,1584.9,1477.5L1584.9,1477.5z M1593.2,1469.2c-0.2,0-0.4-0.1-0.5-0.2l-3.5-3.3c-2.3-2.4-6.2-2.4-8.5,0c-0.6,0.6-1.1,1.4-1.4,2.3c-0.1,0.4-0.6,0.6-0.9,0.4c-0.4-0.1-0.6-0.5-0.4-0.9c1.4-3.9,5.7-5.9,9.6-4.6c1.1,0.4,2,1,2.8,1.8l3.5,3.3c0.3,0.3,0.3,0.7,0,1C1593.6,1469.1,1593.4,1469.2,1593.2,1469.2L1593.2,1469.2z"
                              ></path>
                            </g>
                          </g>
                        </g>
                      </svg>
                      Loading...
                    </div>
                    <div v-else class="common-box bg-gray">
                      <ul class="thead">
                        <li>
                          <div class="categary-name sorting flex60">
                            <span>Asset Name</span>
                          </div>
                          <div class="asset-size sorting flex15">
                            <span>Asset Size</span>
                          </div>
                          <div class="asset-types sorting flex15">
                            <span>Asset Type</span>
                          </div>
                          <div
                            class="total-download sorting flex10 text-center"
                          >
                            <span>Total Download</span>
                          </div>
                        </li>
                      </ul>

                      <ul class="tbody">
                        <template v-if="url.assetsList.length">
                          <li
                            v-for="(file, assetsIndex) in url.assetsList"
                            :key="file.id"
                            class="collectionImage h-auto open"
                          >
                            <div class="w-100 d-flex align-items-center">
                              <a
                                v-if="file.version_count > 1"
                                class="second-lavel"
                                :href="`#img${assetsIndex}${url.id}${file.id}`"
                                aria-expanded="false"
                                data-toggle="collapse"
                                @click.prevent="
                                  getSharedUrlAssetsVersionDetails(
                                    index,
                                    assetsIndex,
                                    url.id,
                                    file
                                  )
                                "
                              >
                                <svg
                                  id="Layer_1"
                                  class="toggle-icon"
                                  version="1.1"
                                  xmlns="http://www.w3.org/2000/svg"
                                  xmlns:xlink="http://www.w3.org/1999/xlink"
                                  x="0px"
                                  y="0px"
                                  viewBox="0 0 18 18"
                                  xml:space="preserve"
                                >
                                  <g
                                    id="Group_4481"
                                    transform="translate(-871 -754)"
                                  >
                                    <rect
                                      id="Rectangle_3019"
                                      x="871"
                                      y="754"
                                      class="fill-hide"
                                      width="18"
                                      height="18"
                                    />
                                    <path
                                      id="Path_3404"
                                      class="fill-color"
                                      d="M880,768.6c-0.5,0-1-0.2-1.3-0.6l-7.1-7.1c-0.7-0.7-0.7-1.9,0-2.7c0.4-0.3,0.8-0.5,1.3-0.5h14.2c1,0,1.9,0.9,1.9,1.9c0,0.5-0.2,1-0.6,1.3l-7.1,7.1C881,768.4,880.5,768.6,880,768.6L880,768.6z M872.9,759.3c-0.2,0-0.3,0.1-0.3,0.3c0,0.1,0,0.2,0.1,0.2l7.1,7.1c0.1,0.1,0.1,0.1,0.2,0.1c0.1,0,0.2,0,0.2-0.1l7.1-7.1c0.1-0.1,0.1-0.3,0-0.4c0,0,0,0,0,0c0-0.1-0.1-0.1-0.2-0.1L872.9,759.3z"
                                    />
                                  </g>
                                </svg>
                              </a>

                              <div class="categary-name tb-column flex60">
                                <div class="media">
                                  <div class="media-left">
                                    <div class="categary-image">
                                      <img
                                        :src="
                                          file.thumbnail_file !== null
                                            ? file.thumbnail_file
                                            : file.preview_image
                                        "
                                        alt=""
                                      />
                                    </div>
                                  </div>

                                  <div class="media-body">
                                    <div class="add-label">
                                      <div class="top-column">
                                        <span>{{
                                          file.display_file_name
                                        }}</span>
                                      </div>
                                      <span
                                        v-if="file.is_deleted"
                                        class="plan-status alert-danger"
                                        >Deleted</span
                                      >
                                      <span
                                        v-else-if="file.is_archive"
                                        class="plan-status alert-primary"
                                        >Archived</span
                                      >
                                    </div>
                                  </div>
                                </div>
                              </div>
                              <div class="asset-size tb-column flex15">
                                <div class="top-column">
                                  <label>{{
                                    $toHumanlySize(file.file_size)
                                  }}</label>
                                </div>
                              </div>

                              <div class="asset-types tb-column flex15">
                                <div class="top-column">
                                  <label>{{ file.file_type }}</label>
                                </div>
                              </div>
                              <div
                                class="total-download tb-column flex10 text-center"
                              >
                                <div class="top-column">
                                  <label>{{ file.total_download }}</label>
                                </div>
                              </div>
                            </div>
                            <div class="h-auto w-100 mt0">
                              <div
                                :id="`img${assetsIndex}${url.id}${file.id}`"
                                class="collapse w-100"
                              >
                                <div
                                  v-if="
                                    assetsVersionDynamicIndex == assetsIndex
                                  "
                                  class="dataLoader"
                                >
                                  <svg
                                    id="Layer_1"
                                    class="refresh-icon fa-spin"
                                    version="1.1"
                                    xmlns="http://www.w3.org/2000/svg"
                                    xmlns:xlink="http://www.w3.org/1999/xlink"
                                    x="0px"
                                    y="0px"
                                    viewBox="0 0 18 18"
                                    xml:space="preserve"
                                  >
                                    <g
                                      id="Group_4491"
                                      transform="translate(-1206 -466)"
                                    >
                                      <rect
                                        id="Rectangle_3030"
                                        x="1206"
                                        y="466"
                                        class="fill-white"
                                        width="18"
                                        height="18"
                                      ></rect>
                                      <g
                                        id="Icon_feather-refresh-cw"
                                        transform="translate(-369.921 -994.994)"
                                      >
                                        <g id="Path_3566">
                                          <path
                                            id="Path_3569"
                                            class="fill-color"
                                            d="M1593.2,1469.2h-4.5c-0.4,0-0.7-0.3-0.7-0.7c0-0.4,0.3-0.7,0.7-0.7h3.8v-3.8c0-0.4,0.3-0.7,0.7-0.7s0.7,0.3,0.7,0.7v4.5C1593.9,1468.9,1593.6,1469.2,1593.2,1469.2z"
                                          ></path>
                                        </g>
                                        <g id="Path_3567">
                                          <path
                                            id="Path_3570"
                                            class="fill-color"
                                            d="M1576.7,1476.7c-0.4,0-0.7-0.3-0.7-0.7v-4.5c0-0.4,0.3-0.7,0.7-0.7h4.5c0.4,0,0.7,0.3,0.7,0.7s-0.3,0.7-0.7,0.7h-3.8v3.8C1577.4,1476.4,1577.1,1476.7,1576.7,1476.7z"
                                          ></path>
                                        </g>
                                        <g id="Path_3568">
                                          <path
                                            id="Path_3571"
                                            class="fill-color"
                                            d="M1584.9,1477.5c-2,0-3.9-0.8-5.3-2.2l-3.5-3.3c-0.3-0.3-0.3-0.7,0-1c0.3-0.3,0.7-0.3,1,0l3.5,3.3c2.3,2.4,6.2,2.4,8.5,0c0.6-0.6,1.1-1.4,1.4-2.3c0.1-0.4,0.5-0.6,0.9-0.5c0.4,0.1,0.6,0.5,0.5,0.9c0,0,0,0,0,0C1590.9,1475.5,1588.1,1477.5,1584.9,1477.5L1584.9,1477.5z M1593.2,1469.2c-0.2,0-0.4-0.1-0.5-0.2l-3.5-3.3c-2.3-2.4-6.2-2.4-8.5,0c-0.6,0.6-1.1,1.4-1.4,2.3c-0.1,0.4-0.6,0.6-0.9,0.4c-0.4-0.1-0.6-0.5-0.4-0.9c1.4-3.9,5.7-5.9,9.6-4.6c1.1,0.4,2,1,2.8,1.8l3.5,3.3c0.3,0.3,0.3,0.7,0,1C1593.6,1469.1,1593.4,1469.2,1593.2,1469.2L1593.2,1469.2z"
                                          ></path>
                                        </g>
                                      </g>
                                    </g>
                                  </svg>
                                  Loading...
                                </div>
                                <div v-else class="common-box bg-gray">
                                  <ul class="thead">
                                    <li>
                                      <div class="categary-name sorting flex50">
                                        <span>Asset Name</span>
                                      </div>
                                      <div class="version sorting flex8">
                                        <span></span>
                                      </div>
                                      <div class="asset-size sorting flex16">
                                        <span>Asset Size</span>
                                      </div>
                                      <div class="asset-types sorting flex16">
                                        <span>Asset Type</span>
                                      </div>
                                      <div
                                        class="total-download sorting flex10 text-center"
                                      >
                                        <span>Total Download</span>
                                      </div>
                                    </li>
                                  </ul>
                                  <ul class="tbody">
                                    <li
                                      v-for="versionFile in file.assetsVersionList"
                                      :key="versionFile.id"
                                      class="collectionVersion h-auto"
                                    >
                                      <div
                                        class="w-100 d-flex align-items-center"
                                      >
                                        <div
                                          class="categary-name tb-column flex58"
                                        >
                                          <div class="media">
                                            <div class="media-left">
                                              <div class="categary-image">
                                                <img
                                                  :src="
                                                    versionFile.thumbnail_file !==
                                                    null
                                                      ? versionFile.thumbnail_file
                                                      : versionFile.preview_image
                                                  "
                                                  alt=""
                                                />
                                              </div>
                                            </div>
                                            <div class="media-body">
                                              <div class="add-label">
                                                <div class="top-column">
                                                  <span>{{
                                                    versionFile.display_file_name
                                                  }}</span>
                                                </div>
                                                <span
                                                  v-if="versionFile.is_deleted"
                                                  class="plan-status alert-danger"
                                                  >Deleted</span
                                                >
                                                <span
                                                  v-else-if="
                                                    versionFile.is_archive
                                                  "
                                                  class="plan-status alert-primary"
                                                  >Archived</span
                                                >
                                              </div>
                                            </div>
                                          </div>
                                        </div>
                                        <div class="version tb-column flex8">
                                          <div class="top-column">
                                            <label
                                              >V{{ versionFile.version }}</label
                                            >
                                          </div>
                                        </div>
                                        <div
                                          class="asset-size tb-column flex16"
                                        >
                                          <div class="top-column">
                                            <label>{{
                                              $toHumanlySize(
                                                versionFile.file_size
                                              )
                                            }}</label>
                                          </div>
                                        </div>
                                        <div
                                          class="asset-types tb-column flex16"
                                        >
                                          <div class="top-column">
                                            <label>{{
                                              versionFile.file_type
                                            }}</label>
                                          </div>
                                        </div>
                                        <div
                                          class="total-download tb-column flex10 text-center"
                                        >
                                          <div class="top-column">
                                            <label>{{
                                              versionFile.total_download
                                            }}</label>
                                          </div>
                                        </div>
                                      </div>
                                    </li>
                                  </ul>
                                </div>
                              </div>
                            </div>
                          </li>
                        </template>
                        <template v-if="url.categoryList.length">
                          <NonCollectionSharedFolder
                            v-for="(file, assetsIndex) in url.categoryList"
                            :key="file.id"
                            :file="file"
                            :url="url"
                            :assets-index="assetsIndex"
                          />
                          <!--                          <li
                            v-for="(file, assetsIndex) in url.categoryList"
                            :key="file.id"
                            class="collectionImage collectionFolder h-auto open"
                          >
                            <div class="w-100 d-flex align-items-center">
                              <a
                                v-if="
                                  file.sub_category_count + file.total_assets >
                                  0
                                "
                                class="second-lavel"
                                :href="`#img${assetsIndex}${url.id}${file.id}`"
                                aria-expanded="false"
                                data-toggle="collapse"
                                @click.prevent="
                                  getSharedUrlAssetsVersionDetails(
                                    index,
                                    assetsIndex,
                                    url.id,
                                    file
                                  )
                                "
                              >
                                <svg
                                  id="Layer_1"
                                  class="toggle-icon"
                                  version="1.1"
                                  xmlns="http://www.w3.org/2000/svg"
                                  xmlns:xlink="http://www.w3.org/1999/xlink"
                                  x="0px"
                                  y="0px"
                                  viewBox="0 0 18 18"
                                  xml:space="preserve"
                                >
                                  <g
                                    id="Group_4481"
                                    transform="translate(-871 -754)"
                                  >
                                    <rect
                                      id="Rectangle_3019"
                                      x="871"
                                      y="754"
                                      class="fill-hide"
                                      width="18"
                                      height="18"
                                    />
                                    <path
                                      id="Path_3404"
                                      class="fill-color"
                                      d="M880,768.6c-0.5,0-1-0.2-1.3-0.6l-7.1-7.1c-0.7-0.7-0.7-1.9,0-2.7c0.4-0.3,0.8-0.5,1.3-0.5h14.2c1,0,1.9,0.9,1.9,1.9c0,0.5-0.2,1-0.6,1.3l-7.1,7.1C881,768.4,880.5,768.6,880,768.6L880,768.6z M872.9,759.3c-0.2,0-0.3,0.1-0.3,0.3c0,0.1,0,0.2,0.1,0.2l7.1,7.1c0.1,0.1,0.1,0.1,0.2,0.1c0.1,0,0.2,0,0.2-0.1l7.1-7.1c0.1-0.1,0.1-0.3,0-0.4c0,0,0,0,0,0c0-0.1-0.1-0.1-0.2-0.1L872.9,759.3z"
                                    />
                                  </g>
                                </svg>
                              </a>

                              <div class="categary-name tb-column flex60">
                                <div class="media">
                                  <div class="media-left">
                                    <div class="categary-image">
                                      <img
                                        :src="
                                          require(file.sub_category_count +
                                            file.total_assets >
                                            0
                                            ? '~/assets/img/folder-icon.svg'
                                            : '~/assets/img/folder-icon2.svg')
                                        "
                                        alt="Folder Icon"
                                      />
                                    </div>
                                  </div>

                                  <div class="media-body">
                                    <div class="top-column">
                                      <span>{{ file.folder_name }}</span>
                                    </div>
                                  </div>
                                </div>
                              </div>
                              <div class="asset-size tb-column flex15">
                                <div class="top-column">
                                  <label>-</label>
                                </div>
                              </div>

                              <div class="asset-types tb-column flex15">
                                <div class="top-column">
                                  <label>-</label>
                                </div>
                              </div>
                              <div
                                class="total-download tb-column flex10 text-center"
                              >
                                <div class="top-column">
                                  <label>-</label>
                                </div>
                              </div>
                            </div>
                            <div class="h-auto w-100 mt0">
                              <div
                                :id="`img${assetsIndex}${url.id}${file.id}`"
                                class="collapse w-100"
                              >
                                <div
                                  v-if="
                                    assetsVersionDynamicIndex == assetsIndex
                                  "
                                  class="dataLoader"
                                >
                                  <svg
                                    id="Layer_1"
                                    class="refresh-icon fa-spin"
                                    version="1.1"
                                    xmlns="http://www.w3.org/2000/svg"
                                    xmlns:xlink="http://www.w3.org/1999/xlink"
                                    x="0px"
                                    y="0px"
                                    viewBox="0 0 18 18"
                                    xml:space="preserve"
                                  >
                                    <g
                                      id="Group_4491"
                                      transform="translate(-1206 -466)"
                                    >
                                      <rect
                                        id="Rectangle_3030"
                                        x="1206"
                                        y="466"
                                        class="fill-white"
                                        width="18"
                                        height="18"
                                      ></rect>
                                      <g
                                        id="Icon_feather-refresh-cw"
                                        transform="translate(-369.921 -994.994)"
                                      >
                                        <g id="Path_3566">
                                          <path
                                            id="Path_3569"
                                            class="fill-color"
                                            d="M1593.2,1469.2h-4.5c-0.4,0-0.7-0.3-0.7-0.7c0-0.4,0.3-0.7,0.7-0.7h3.8v-3.8c0-0.4,0.3-0.7,0.7-0.7s0.7,0.3,0.7,0.7v4.5C1593.9,1468.9,1593.6,1469.2,1593.2,1469.2z"
                                          ></path>
                                        </g>
                                        <g id="Path_3567">
                                          <path
                                            id="Path_3570"
                                            class="fill-color"
                                            d="M1576.7,1476.7c-0.4,0-0.7-0.3-0.7-0.7v-4.5c0-0.4,0.3-0.7,0.7-0.7h4.5c0.4,0,0.7,0.3,0.7,0.7s-0.3,0.7-0.7,0.7h-3.8v3.8C1577.4,1476.4,1577.1,1476.7,1576.7,1476.7z"
                                          ></path>
                                        </g>
                                        <g id="Path_3568">
                                          <path
                                            id="Path_3571"
                                            class="fill-color"
                                            d="M1584.9,1477.5c-2,0-3.9-0.8-5.3-2.2l-3.5-3.3c-0.3-0.3-0.3-0.7,0-1c0.3-0.3,0.7-0.3,1,0l3.5,3.3c2.3,2.4,6.2,2.4,8.5,0c0.6-0.6,1.1-1.4,1.4-2.3c0.1-0.4,0.5-0.6,0.9-0.5c0.4,0.1,0.6,0.5,0.5,0.9c0,0,0,0,0,0C1590.9,1475.5,1588.1,1477.5,1584.9,1477.5L1584.9,1477.5z M1593.2,1469.2c-0.2,0-0.4-0.1-0.5-0.2l-3.5-3.3c-2.3-2.4-6.2-2.4-8.5,0c-0.6,0.6-1.1,1.4-1.4,2.3c-0.1,0.4-0.6,0.6-0.9,0.4c-0.4-0.1-0.6-0.5-0.4-0.9c1.4-3.9,5.7-5.9,9.6-4.6c1.1,0.4,2,1,2.8,1.8l3.5,3.3c0.3,0.3,0.3,0.7,0,1C1593.6,1469.1,1593.4,1469.2,1593.2,1469.2L1593.2,1469.2z"
                                          ></path>
                                        </g>
                                      </g>
                                    </g>
                                  </svg>
                                  Loading...
                                </div>
                                <div v-else class="common-box bg-gray pl0">
                                  <ul class="tbody">
                                    &lt;!&ndash;                                    <template
                                      v-if="file.categoryVersionList.length"
                                    >
                                      <li
                                        v-for="versionFile in file.categoryVersionList"
                                        :key="versionFile.id"
                                        class="collectionVersion collectionFolder h-auto"
                                      >
                                        <div
                                          class="w-100 d-flex align-items-center"
                                        >
                                          <div
                                            class="categary-name tb-column flex60"
                                          >
                                            <div class="media">
                                              <div class="media-left">
                                                <div class="categary-image">
                                                  <img
                                                    :src="
                                                      require(versionFile.sub_category_count +
                                                        versionFile.total_assets >
                                                        0 >
                                                        0
                                                        ? '~/assets/img/folder-icon.svg'
                                                        : '~/assets/img/folder-icon2.svg')
                                                    "
                                                    alt="Folder Icon"
                                                  />
                                                </div>
                                              </div>
                                              <div class="media-body">
                                                <div class="top-column">
                                                  <span>{{
                                                    versionFile.folder_name
                                                  }}</span>
                                                </div>
                                              </div>
                                            </div>
                                          </div>
                                          <div
                                            class="asset-size tb-column flex15"
                                          >
                                            <div class="top-column">
                                              <label>- </label>
                                            </div>
                                          </div>
                                          <div
                                            class="asset-types tb-column flex15"
                                          >
                                            <div class="top-column">
                                              <label>-</label>
                                            </div>
                                          </div>
                                          <div
                                            class="total-download tb-column flex10 text-center"
                                          >
                                            <div class="top-column">
                                              <label>-</label>
                                            </div>
                                          </div>
                                        </div>
                                      </li>
                                    </template>&ndash;&gt;
                                    <template
                                      v-if="file.assetsVersionList.length"
                                    >
                                      <li
                                        v-for="(
                                          versionFile, assetsVersionIndex
                                        ) in file.assetsVersionList"
                                        :key="versionFile.id"
                                        class="h-auto"
                                        :class="[
                                          versionFile.version_count > 1
                                            ? 'collectionImage open'
                                            : 'collectionVersion collectionFolder',
                                        ]"
                                      >
                                        <div
                                          class="w-100 d-flex align-items-center"
                                        >
                                          <a
                                            v-if="versionFile.version_count > 1"
                                            class="second-lavel"
                                            :href="`#img${assetsVersionIndex}${url.id}${file.id}${versionFile.id}`"
                                            aria-expanded="false"
                                            data-toggle="collapse"
                                            @click.prevent="
                                              getAssetsVersionDetails(
                                                index,
                                                assetsIndex,
                                                assetsVersionIndex,
                                                url.id,
                                                file.id,
                                                versionFile
                                              )
                                            "
                                          >
                                            <svg
                                              id="Layer_1"
                                              class="toggle-icon"
                                              version="1.1"
                                              xmlns="http://www.w3.org/2000/svg"
                                              xmlns:xlink="http://www.w3.org/1999/xlink"
                                              x="0px"
                                              y="0px"
                                              viewBox="0 0 18 18"
                                              xml:space="preserve"
                                            >
                                              <g
                                                id="Group_4481"
                                                transform="translate(-871 -754)"
                                              >
                                                <rect
                                                  id="Rectangle_3019"
                                                  x="871"
                                                  y="754"
                                                  class="fill-hide"
                                                  width="18"
                                                  height="18"
                                                />
                                                <path
                                                  id="Path_3404"
                                                  class="fill-color"
                                                  d="M880,768.6c-0.5,0-1-0.2-1.3-0.6l-7.1-7.1c-0.7-0.7-0.7-1.9,0-2.7c0.4-0.3,0.8-0.5,1.3-0.5h14.2c1,0,1.9,0.9,1.9,1.9c0,0.5-0.2,1-0.6,1.3l-7.1,7.1C881,768.4,880.5,768.6,880,768.6L880,768.6z M872.9,759.3c-0.2,0-0.3,0.1-0.3,0.3c0,0.1,0,0.2,0.1,0.2l7.1,7.1c0.1,0.1,0.1,0.1,0.2,0.1c0.1,0,0.2,0,0.2-0.1l7.1-7.1c0.1-0.1,0.1-0.3,0-0.4c0,0,0,0,0,0c0-0.1-0.1-0.1-0.2-0.1L872.9,759.3z"
                                                />
                                              </g>
                                            </svg>
                                          </a>
                                          <div
                                            class="categary-name tb-column flex60"
                                          >
                                            <div class="media">
                                              <div class="media-left">
                                                <div class="categary-image">
                                                  <img
                                                    :src="
                                                      versionFile.thumbnail_file !==
                                                      null
                                                        ? versionFile.thumbnail_file
                                                        : versionFile.preview_image
                                                    "
                                                    alt=""
                                                  />
                                                </div>
                                              </div>
                                              <div class="media-body">
                                                <div class="top-column">
                                                  <span>{{
                                                    versionFile.display_file_name
                                                  }}</span>
                                                </div>
                                              </div>
                                            </div>
                                          </div>
                                          <div
                                            class="asset-size tb-column flex15"
                                          >
                                            <div class="top-column">
                                              <label
                                                >{{
                                                  $toHumanlySize(
                                                    versionFile.file_size
                                                  )
                                                }}
                                              </label>
                                            </div>
                                          </div>
                                          <div
                                            class="asset-types tb-column flex15"
                                          >
                                            <div class="top-column">
                                              <label>{{
                                                versionFile.file_type
                                              }}</label>
                                            </div>
                                          </div>
                                          <div
                                            class="total-download tb-column flex10 text-center"
                                          >
                                            <div class="top-column">
                                              <label>{{
                                                versionFile.total_download
                                              }}</label>
                                            </div>
                                          </div>
                                        </div>

                                        <div class="h-auto w-100 mt0">
                                          <div
                                            :id="`img${assetsVersionIndex}${url.id}${file.id}${versionFile.id}`"
                                            class="collapse w-100"
                                          >
                                            <div
                                              v-if="
                                                assetsVersionDynamicIndex ==
                                                assetsVersionIndex
                                              "
                                              class="dataLoader"
                                            >
                                              <svg
                                                id="Layer_1"
                                                class="refresh-icon fa-spin"
                                                version="1.1"
                                                xmlns="http://www.w3.org/2000/svg"
                                                xmlns:xlink="http://www.w3.org/1999/xlink"
                                                x="0px"
                                                y="0px"
                                                viewBox="0 0 18 18"
                                                xml:space="preserve"
                                              >
                                                <g
                                                  id="Group_4491"
                                                  transform="translate(-1206 -466)"
                                                >
                                                  <rect
                                                    id="Rectangle_3030"
                                                    x="1206"
                                                    y="466"
                                                    class="fill-white"
                                                    width="18"
                                                    height="18"
                                                  ></rect>
                                                  <g
                                                    id="Icon_feather-refresh-cw"
                                                    transform="translate(-369.921 -994.994)"
                                                  >
                                                    <g id="Path_3566">
                                                      <path
                                                        id="Path_3569"
                                                        class="fill-color"
                                                        d="M1593.2,1469.2h-4.5c-0.4,0-0.7-0.3-0.7-0.7c0-0.4,0.3-0.7,0.7-0.7h3.8v-3.8c0-0.4,0.3-0.7,0.7-0.7s0.7,0.3,0.7,0.7v4.5C1593.9,1468.9,1593.6,1469.2,1593.2,1469.2z"
                                                      ></path>
                                                    </g>
                                                    <g id="Path_3567">
                                                      <path
                                                        id="Path_3570"
                                                        class="fill-color"
                                                        d="M1576.7,1476.7c-0.4,0-0.7-0.3-0.7-0.7v-4.5c0-0.4,0.3-0.7,0.7-0.7h4.5c0.4,0,0.7,0.3,0.7,0.7s-0.3,0.7-0.7,0.7h-3.8v3.8C1577.4,1476.4,1577.1,1476.7,1576.7,1476.7z"
                                                      ></path>
                                                    </g>
                                                    <g id="Path_3568">
                                                      <path
                                                        id="Path_3571"
                                                        class="fill-color"
                                                        d="M1584.9,1477.5c-2,0-3.9-0.8-5.3-2.2l-3.5-3.3c-0.3-0.3-0.3-0.7,0-1c0.3-0.3,0.7-0.3,1,0l3.5,3.3c2.3,2.4,6.2,2.4,8.5,0c0.6-0.6,1.1-1.4,1.4-2.3c0.1-0.4,0.5-0.6,0.9-0.5c0.4,0.1,0.6,0.5,0.5,0.9c0,0,0,0,0,0C1590.9,1475.5,1588.1,1477.5,1584.9,1477.5L1584.9,1477.5z M1593.2,1469.2c-0.2,0-0.4-0.1-0.5-0.2l-3.5-3.3c-2.3-2.4-6.2-2.4-8.5,0c-0.6,0.6-1.1,1.4-1.4,2.3c-0.1,0.4-0.6,0.6-0.9,0.4c-0.4-0.1-0.6-0.5-0.4-0.9c1.4-3.9,5.7-5.9,9.6-4.6c1.1,0.4,2,1,2.8,1.8l3.5,3.3c0.3,0.3,0.3,0.7,0,1C1593.6,1469.1,1593.4,1469.2,1593.2,1469.2L1593.2,1469.2z"
                                                      ></path>
                                                    </g>
                                                  </g>
                                                </g>
                                              </svg>
                                              Loading...
                                            </div>
                                            <div
                                              v-else
                                              class="common-box bg-gray"
                                            >
                                              <ul class="thead">
                                                <li>
                                                  <div
                                                    class="categary-name sorting flex50"
                                                  >
                                                    <span>Asset Name</span>
                                                  </div>
                                                  <div
                                                    class="version sorting flex8"
                                                  >
                                                    <span></span>
                                                  </div>
                                                  <div
                                                    class="asset-size sorting flex16"
                                                  >
                                                    <span>Asset Size</span>
                                                  </div>
                                                  <div
                                                    class="asset-types sorting flex16"
                                                  >
                                                    <span>Asset Type</span>
                                                  </div>
                                                  <div
                                                    class="total-download sorting flex10 text-center"
                                                  >
                                                    <span>Total Download</span>
                                                  </div>
                                                </li>
                                              </ul>
                                              <ul class="tbody">
                                                <li
                                                  v-for="versionFileAssets in versionFile.assetsVersion2List"
                                                  :key="versionFileAssets.id"
                                                  class="collectionVersion h-auto"
                                                >
                                                  <div
                                                    class="w-100 d-flex align-items-center"
                                                  >
                                                    <div
                                                      class="categary-name tb-column flex58"
                                                    >
                                                      <div class="media">
                                                        <div class="media-left">
                                                          <div
                                                            class="categary-image"
                                                          >
                                                            <img
                                                              :src="
                                                                versionFileAssets.thumbnail_file !==
                                                                null
                                                                  ? versionFileAssets.thumbnail_file
                                                                  : versionFileAssets.preview_image
                                                              "
                                                              alt=""
                                                            />
                                                          </div>
                                                        </div>
                                                        <div class="media-body">
                                                          <div
                                                            class="top-column"
                                                          >
                                                            <span>{{
                                                              versionFileAssets.display_file_name
                                                            }}</span>
                                                          </div>
                                                        </div>
                                                      </div>
                                                    </div>
                                                    <div
                                                      class="version tb-column flex8"
                                                    >
                                                      <div class="top-column">
                                                        <label
                                                          >V{{
                                                            versionFileAssets.version
                                                          }}</label
                                                        >
                                                      </div>
                                                    </div>
                                                    <div
                                                      class="asset-size tb-column flex16"
                                                    >
                                                      <div class="top-column">
                                                        <label>{{
                                                          $toHumanlySize(
                                                            versionFileAssets.file_size
                                                          )
                                                        }}</label>
                                                      </div>
                                                    </div>
                                                    <div
                                                      class="asset-types tb-column flex16"
                                                    >
                                                      <div class="top-column">
                                                        <label>{{
                                                          versionFileAssets.file_type
                                                        }}</label>
                                                      </div>
                                                    </div>
                                                    <div
                                                      class="total-download tb-column flex10 text-center"
                                                    >
                                                      <div class="top-column">
                                                        <label>{{
                                                          versionFileAssets.total_download
                                                        }}</label>
                                                      </div>
                                                    </div>
                                                  </div>
                                                </li>
                                              </ul>
                                            </div>
                                          </div>
                                        </div>
                                      </li>
                                    </template>
                                  </ul>
                                </div>
                              </div>
                            </div>
                          </li>-->
                        </template>
                      </ul>
                    </div>
                  </div>
                </div>
              </li>
              <client-only>
                <infinite-loading
                  :identifier="infiniteId"
                  @infinite="infiniteHandler"
                >
                  <div slot="spinner">
                    <ContentLoader
                      v-if="page == 1"
                      :speed="1"
                      :animate="true"
                      :width="400"
                      :height="100"
                    >
                      <rect
                        x="0"
                        y="-1"
                        rx="0"
                        ry="0"
                        width="400"
                        height="13"
                      />
                      <rect
                        x="0"
                        y="15"
                        rx="0"
                        ry="0"
                        width="400"
                        height="13"
                      />
                      <rect
                        x="0"
                        y="31"
                        rx="0"
                        ry="0"
                        width="400"
                        height="13"
                      />
                      <rect
                        x="0"
                        y="47"
                        rx="0"
                        ry="0"
                        width="400"
                        height="13"
                      />
                    </ContentLoader>
                    <div v-else class="no-data-found pb2 pt2">
                      <div class="inner w-100">
                        <p>Loading...</p>
                      </div>
                    </div>
                  </div>
                  <div slot="no-more"></div>
                  <div slot="no-results">
                    <EmptyState v-if="!sharedUrlList.length" />
                  </div>
                </infinite-loading>
              </client-only>
            </ul>
          </div>
        </div>
      </div>
      <!--  View By - Assets   -->
      <SharedUrlByAssetsView
        v-if="viewedBy == 'assets'"
        :collection-chart-type="collectionChartType"
        :category-by="categoryBy"
        :collections-type="collectionsType"
        :start-date="startDate"
        :end-date="endDate"
      />
    </div>
  </div>
</template>
<script>
import { ContentLoader } from 'vue-content-loader'
import Select2 from '~/components/plugins/Select2'
import analytics from '~/mixins/analytics'
import EmptyState from '~/components/theme/global/EmptyState'
import damShareUrl from '~/mixins/damShareUrl'

import SharedUrlByAssetsView from '~/components/dam/DamAnalytics/SharedAssets/SharedUrlByAssetsView'
import NonCollectionSharedFolder from '~/components/dam/DamAnalytics/SharedAssets/NonCollectionSharedFolder'

export default {
  components: {
    ContentLoader,
    Select2,
    EmptyState,
    SharedUrlByAssetsView,
    NonCollectionSharedFolder,
  },
  mixins: [analytics, damShareUrl],
  props: {
    chartType: { type: String, required: true },
    breadcrumbsHeader: { type: String, required: true },
    loadCategoryList: { type: String, required: true },
    category: { type: String, required: true },
    startDate: { type: [Date, String, Object] },
    endDate: { type: [Date, String, Object] },
    categoryByCollection: { type: String, required: false },
    categoryByShared: { type: String, required: false },
  },
  data() {
    return {
      categoryBy: this.category,
      sharedUrlList: [],
      collectionChartType: this.chartType,
      collectionBreadcrumbsHeader: this.breadcrumbsHeader,
      collectionsType: this.categoryByCollection,
      viewedBy: this.categoryByShared,
      completelyLoaded: false,
      isSortComplete: false,
      infiniteId: +new Date(),
      page: 1,
      lastPage: null,
      sort_value: '',
      sort_by: 'ASC',
      assetsDynamicIndex: null,
      assetsVersionDynamicIndex: null,
    }
  },
  computed: {
    categoryList() {
      let x = null
      switch (this.loadCategoryList) {
        case 'collectionSharedUrl':
          x = this.userTypeList
          break
        case 'nonCollectionSharedUrl':
          x = this.userTypeList
          break
      }
      return x
    },
  },
  methods: {
    changeCategory(value) {
      this.categoryBy = value
      this.resetSharedUrlList()
    },
    changeCategoryByCollection(value) {
      this.collectionsType = value
      if (this.collectionsType === 'collection') {
        this.collectionChartType = 'collectionSharedUrl'
        this.collectionBreadcrumbsHeader = 'Collection Shared URLs'
      } else {
        this.collectionChartType = 'nonCollectionSharedUrl'
        this.collectionBreadcrumbsHeader = 'Non Collection Shared URLs'
      }
      this.resetSharedUrlList()
    },
    changeCategoryByShared(value) {
      this.viewedBy = value
      if (this.viewedBy === 'shared url') {
        this.resetSharedUrlList()
      }
    },
    sortByColumn(column) {
      this.sort_value = column
      this.sort_by = this.sort_by === 'ASC' ? 'DESC' : 'ASC'
      this.resetSharedUrlList()
    },
    sortingClass(sortValue) {
      return {
        active: this.sort_value === sortValue && this.sort_by === 'DESC',
      }
    },
    resetSharedUrlList() {
      this.sharedUrlList = []
      this.page = 1
      this.infiniteId += 1
      this.completelyLoaded = false
      this.isSortComplete = false
    },
    infiniteHandler($state) {
      if (this.completelyLoaded || this.isSortComplete) {
        $state.complete()
        return
      }
      if (this.collectionChartType === 'collectionSharedUrl') {
        this.getCollectionSharedUrlList($state)
      }
      if (this.collectionChartType === 'nonCollectionSharedUrl') {
        this.getNonCollectionSharedUrlList($state)
      }
    },
    async getCollectionSharedUrlList($state) {
      let userType = this.categoryBy
      if (this.categoryBy === 'frontend users') {
        userType = 'frontend_user'
      }
      await this.$axios
        .$post(
          `digital-assets/analytics/collection-share-url-details?page=${this.page}`,
          {
            from_date: this.startDate,
            to_date: this.endDate,
            user_type: userType,
          }
        )
        .then(({ data }) => {
          this.lastPage = data.last_page

          if (data.data && data.data.length) {
            if (parseInt(this.page) === parseInt(data.current_page)) {
              this.sharedUrlList.push(
                ...data.data.map((item) => ({
                  ...item,
                  assetsList: [],
                  categoryList: [],
                  expand: false,
                }))
              )
              $state.loaded()
              if (parseInt(this.lastPage) === parseInt(this.page)) {
                this.completelyLoaded = true
                $state.complete()
              } else {
                this.page += 1
              }
            } else {
              $state.complete()
            }
          } else {
            $state.complete()
          }
        })
        .catch((e) => {
          $state.error()
        })
        .finally(() => this.$nextTick(() => (this.isSortComplete = false)))
    },
    async getNonCollectionSharedUrlList($state) {
      let userType = this.categoryBy
      if (this.categoryBy === 'frontend users') {
        userType = 'frontend_user'
      }
      await this.$axios
        .$post(
          `digital-assets/analytics/non-collection-share-url-details?page=${this.page}`,
          {
            from_date: this.startDate,
            to_date: this.endDate,
            user_type: userType,
          }
        )
        .then(({ data }) => {
          this.lastPage = data.last_page
          if (data.data && data.data.length) {
            if (parseInt(this.page) === parseInt(data.current_page)) {
              this.sharedUrlList.push(
                ...data.data.map((item) => ({
                  ...item,
                  assetsList: [],
                  categoryList: [],
                  expand: false,
                }))
              )
              $state.loaded()
              if (parseInt(this.lastPage) === parseInt(this.page)) {
                this.completelyLoaded = true
                $state.complete()
              } else {
                this.page += 1
              }
            } else {
              $state.complete()
            }
          } else {
            $state.complete()
          }
        })
        .catch((e) => {
          $state.error()
        })
        .finally(() => this.$nextTick(() => (this.isSortComplete = false)))
    },
    async getSharedUrlAssetsDetails(index, url) {
      this.sharedUrlList[index].expand = !this.sharedUrlList[index].expand
      let userType = this.categoryBy
      if (this.categoryBy === 'frontend users') {
        userType = 'frontend_user'
      }
      if (this.sharedUrlList[index].expand) {
        !this.sharedUrlList[index].assetsList.length &&
          (this.assetsDynamicIndex = index)
        !this.sharedUrlList[index].categoryList.length &&
          (this.assetsDynamicIndex = index)
        await this.$axios
          .$post(
            this.collectionsType === 'collection'
              ? 'digital-assets/analytics/collection-share-url-assets-details'
              : 'digital-assets/analytics/non-collection-share-url-assets-details',
            {
              user_type: userType,
              share_id: url.id,
            }
          )
          .then(({ data }) => {
            if (this.collectionsType === 'collection') {
              this.sharedUrlList[index].assetsList = data.map((item) => ({
                ...item,
                assetsVersionList: [],
                expand: false,
              }))
            } else {
              if (data.assets && data.assets.length) {
                this.sharedUrlList[index].assetsList = data.assets.map(
                  (item) => ({
                    ...item,
                    assetsVersionList: [],
                    expand: false,
                  })
                )
              }
              if (data.category && data.category.length) {
                this.sharedUrlList[index].categoryList = data.category.map(
                  (item) => ({
                    ...item,
                    assetsVersionList: [],
                    expand: false,
                  })
                )
              }
            }
            this.assetsDynamicIndex = null
          })
          .catch(this.$errorToast)
      }
    },

    async getSharedUrlAssetsVersionDetails(
      urlIndex,
      assetsIndex,
      sharedId,
      file
    ) {
      this.sharedUrlList[urlIndex].assetsList[assetsIndex].expand =
        !this.sharedUrlList[urlIndex].assetsList[assetsIndex].expand
      if (this.sharedUrlList[urlIndex].assetsList[assetsIndex].expand) {
        this.sharedUrlList[urlIndex].assetsList[assetsIndex].assetsVersionList =
          []
        !this.sharedUrlList[urlIndex].assetsList[assetsIndex].assetsVersionList
          .length && (this.assetsVersionDynamicIndex = assetsIndex)
        await this.$axios
          .$post('digital-assets/analytics/share-url-assets-version-details', {
            asset_id: file.id,
            share_id: sharedId,
          })
          .then(({ data }) => {
            this.sharedUrlList[urlIndex].assetsList[
              assetsIndex
            ].assetsVersionList = data
            this.assetsVersionDynamicIndex = null
          })
          .catch(this.$errorToast)
      }
    },
  },
}
</script>
